config/routes.rb
Rails.application.routes.draw do
  
  #avtive_admin用のルート
  ActiveAdmin.routes(self)
  
  root "static_pages#home"
  get "/about", to:"static_pages#about"
  get '/signup', to: "users#new"
  post "/signup", to: "users#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/auth/:provider/callback", to: 'sessions#twitter_create', as: 'tlogin'
  delete "/logout", to: "sessions#destroy"
  
  resources :users
  
  resources :recipes do
    member do
      get :liked #レシピをイイネしたユーザーの一覧
      patch :release #公開・非公開を決めるカラム
    end
  end
  patch "recipes/:id/edit", to: "recipes#update", as: "update_recipe"

  resources :ingredients, only: :create
  
  resources :procedures, only: :create
  patch "procedures/update", to: "procedures#update"
  delete "procedures/destroy", to: "procedures#destroy"
  post "procedures/change_after", to: "procedures#change_after"
  post "procedures/change_before", to: "procedures#change_before"
  
  resources :likes, only: [:create, :destroy]
  
  resources :books, only: [:create,:destroy]
  
  resources :impressions, only: [:create, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  #リレーション
  belongs_to :user
  has_many :ingredient, dependent: :destroy
  has_many :procedure, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :impressions, dependent: :destroy
  
  #アップローダー
  mount_uploader :image, ImageUploader
  validate :image_size
  
  #バリデーション
  validates :name,presence: true, length: {maximum: 20}
  
  private
  
    #アップロードされた画像のサイズをバリデーション
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "画像サイズは5MB以内です")
      end
    end
  
    #キーワードに対応したレシピを返す
    def self.search(search)
      #検索ワードが空なら公開レシピをすべて取得
      return Recipe.where(release: true) unless search
      #検索ワードに似たレシピを返す
      Recipe.where(release: true).where("name LIKE ?", "%#{search}%")
    end
    
    #レシピを時系列で返す
    def self.latest(limit_number = nil)
      #取得数の指定がなければすべてのレコードを取得
      return Recipe.where(release: true).order(created_at: "DESC") unless limit_number
      #指定された数のレコードを取得
      Recipe.where(release: true).order(updated_at: "DESC").limit(limit_number)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_author, only: [:new, :create, :edit]
  before_action :correct_author, only:[:edit, :update, :release, :destroy]
  
  def index
    @keyword = params[:search] 
    @recipes_count = Recipe.search(@keyword)
    @recipes = @recipes_count.order(updated_at: "DESC").page(params[:page]).per(20)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      @recipe.procedure.create(number: 1, content: "")
      @recipe.ingredient.create(number: 1)
      redirect_to edit_recipe_path(@recipe)
    else
      render "new"
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
    @ingredients = IngredientCollection.new( [], @recipe)
    @procedures = @recipe.procedure.order(number: "ASC")
    @procedure = @recipe.procedure.build
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      respond_to do |format|
        format.html {redirect_to edit_recipe_path(@recipe)}
        format.js
      end
    else
      @ingredients = IngredientCollection.new( [], @recipe)
      @procedures = @recipe.procedure.order(number: "ASC")
      render "edit"
    end
  end
  
  #@recipe,@userはcorrect_userで設定
  def destroy
    @recipe.destroy
    flash[:success] = "レシピを削除しました"
    redirect_to user_path(@user)
  end
  
  def release
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(release: params[:release])
      if @recipe.release == true
        flash[:success] = "レシピを公開しました"
        redirect_to recipe_path(@recipe)
      else
        flash[:success] = "レシピを下書きにしました"
        redirect_to user_path(id: @recipe.user_id)
      end
    else
      render "edit"
    end
  end
  
  def liked
    @recipe = Recipe.find(params[:id])
    @liked_user = @recipe.likes.page(params[:page])
  end
  
  def show
    @recipe = Recipe.find_by(id: params[:id])
    if @recipe.present?
      @tweet_url = URI.encode(
        "http://twitter.com/intent/tweet?original_referer=" +
        request.url +
        "&url=" +
        request.url +
        "&text=" +
        @recipe.name + "のレシピを見ています！"
      )
      @user_comments = @recipe.impressions.page(params[:page]).per(5)
    else
      flash[:danger] = "レシピが見つかりませんでした"
      redirect_to root_url
    end
  end
  
  private
  
    #Recipeのストロングパラメーター
    def recipe_params
      params.require(:recipe).permit(:name, :comment, :image, :image_cache)
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
  
    #ログイン済ユーザーかどうか確認
    def logged_in_author
      unless logged_in?
        store_location
        flash[:danger] = "レシピの閲覧・投稿・編集にはログインが必要です。"
        redirect_to login_url
      end
    end
    
    #URLからレシピＩＤを取得。
    def recipe_author
      @recipe = Recipe.find_by(id: params[:id])
      @user = @recipe.user
    end
    
    #フォームのパラメーターからレシピIDを取得
    def recipe_author_via
      @recipe = Recipe.find_by(id: params[:recipe_id])
      @user = @recipe.user
    end
    
    #recipe_authorメソッドでユーザー情報を取得
    def correct_author
      recipe_author
      redirect_to(root_url) unless current_user?(@user)
    end
    
    #recipe_author_viaメソッドでユーザー情報を取得
    def correct_author_via
      recipe_author_via
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/views/recipes/edit/_commentform.html.erb
<div id="recipe-comment-show">
  <% if @recipe.comment.present? %>
  	<%= @recipe.comment %>
  <% else %>
  	<p>コメントを入力しましょう。</p>
  <% end %>
</div>
<dt><a>コメントを変更する</a></dt>
<dd>
  <%= form_with model: @recipe do |f| %>
    <%= f.text_area :comment, placeholder: "コメントを入力しましょう", value: @recipe.comment %>
    <div class="btn-right">
      <%= f.submit "保存" , class: "btn mini-btn"%>
    </div>
  <% end %>
</dd>

app/views/recipes/edit/_nameform.html.erb
<%= form_with model: @recipe do |f| %>
  <%= f.text_area :name, placeholder: "レシピの名前を入力しましょう", value: @recipe.name %>
  <div class="btn-right">
  	<%= f.submit "変更", class: "btn mini-btn"%>
  </div>
<% end %>

app/views/recipes/edit/_privateform.html.erb
<%= form_with url: release_recipe_path(@recipe), method: :patch, local: true do |f| %>
  <%= f.hidden_field :release, value: false %>
  <%= f.submit "プライベートで保存" ,class: "btn midium-btn"%>
<% end %>

app/views/recipes/edit/_releaseform.html.erb
<%= form_with url: release_recipe_path(@recipe), method: :patch, local: true do |f| %>
  <%= f.hidden_field :release, value: true %>
  <%= f.submit "レシピを公開する", class: "important-btn large-btn" %>
<% end %>

app/views/recipes/edit/_uploader.html.erb
<%= form_with model: @recipe, url: update_recipe_path, local: true do |f| %>
	<%= render "shared/error_messages", object: f.object %>
	<%= f.hidden_field :image_cache %>
	<%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" ,class: "mb-s"%>
	<div>
		<%= button_tag type:"submit", class: "clear-btn" do %>
			<%= icon('fas','camera') %><%= "イメージを登録" %>
		<% end %>
	</div>
<% end %>