config/routes.rb
Rails.application.routes.draw do
  
  #avtive_admin用のルート
  ActiveAdmin.routes(self)
  
  root "static_pages#home"
  get "/about", to:"static_pages#about"
  get '/signup', to: "users#new"
  post "/signup", to: "users#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/auth/:provider/callback", to: 'sessions#twitter_create', as: 'tlogin'
  delete "/logout", to: "sessions#destroy"
  
  resources :users
  
  resources :recipes do
    member do
      get :liked #レシピをイイネしたユーザーの一覧
      patch :release #公開・非公開を決めるカラム
    end
  end
  patch "recipes/:id/edit", to: "recipes#update", as: "update_recipe"

  resources :ingredients, only: :create
  
  resources :procedures, only: :create
  patch "procedures/update", to: "procedures#update"
  delete "procedures/destroy", to: "procedures#destroy"
  post "procedures/change_after", to: "procedures#change_after"
  post "procedures/change_before", to: "procedures#change_before"
  
  resources :likes, only: [:create, :destroy]
  
  resources :books, only: [:create,:destroy]
  
  resources :impressions, only: [:create, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  #リレーション
  belongs_to :user
  has_many :ingredient, dependent: :destroy
  has_many :procedure, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :impressions, dependent: :destroy
  
  #アップローダー
  mount_uploader :image, ImageUploader
  validate :image_size
  
  #バリデーション
  validates :name,presence: true, length: {maximum: 20}
  
  private
  
    #アップロードされた画像のサイズをバリデーション
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "画像サイズは5MB以内です")
      end
    end
  
    #キーワードに対応したレシピを返す
    def self.search(search)
      #検索ワードが空なら公開レシピをすべて取得
      return Recipe.where(release: true) unless search
      #検索ワードに似たレシピを返す
      Recipe.where(release: true).where("name LIKE ?", "%#{search}%")
    end
    
    #レシピを時系列で返す
    def self.latest(limit_number = nil)
      #取得数の指定がなければすべてのレコードを取得
      return Recipe.where(release: true).order(created_at: "DESC") unless limit_number
      #指定された数のレコードを取得
      Recipe.where(release: true).order(updated_at: "DESC").limit(limit_number)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_author, only: [:new, :create, :edit]
  before_action :correct_author, only:[:edit, :update, :release, :destroy]
  
  def index
    @keyword = params[:search] 
    @recipes_count = Recipe.search(@keyword)
    @recipes = @recipes_count.order(updated_at: "DESC").page(params[:page]).per(20)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      @recipe.procedure.create(number: 1, content: "")
      @recipe.ingredient.create(number: 1)
      redirect_to edit_recipe_path(@recipe)
    else
      render "new"
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
    @ingredients = IngredientCollection.new( [], @recipe)
    @procedures = @recipe.procedure.order(number: "ASC")
    @procedure = @recipe.procedure.build
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      respond_to do |format|
        format.html {redirect_to edit_recipe_path(@recipe)}
        format.js
      end
    else
      @ingredients = IngredientCollection.new( [], @recipe)
      @procedures = @recipe.procedure.order(number: "ASC")
      render "edit"
    end
  end
  
  #@recipe,@userはcorrect_userで設定
  def destroy
    @recipe.destroy
    flash[:success] = "レシピを削除しました"
    redirect_to user_path(@user)
  end
  
  def release
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(release: params[:release])
      if @recipe.release == true
        flash[:success] = "レシピを公開しました"
        redirect_to recipe_path(@recipe)
      else
        flash[:success] = "レシピを下書きにしました"
        redirect_to user_path(id: @recipe.user_id)
      end
    else
      render "edit"
    end
  end
  
  def liked
    @recipe = Recipe.find(params[:id])
    @liked_user = @recipe.likes.page(params[:page])
  end
  
  def show
    @recipe = Recipe.find_by(id: params[:id])
    if @recipe.present?
      @tweet_url = URI.encode(
        "http://twitter.com/intent/tweet?original_referer=" +
        request.url +
        "&url=" +
        request.url +
        "&text=" +
        @recipe.name + "のレシピを見ています！"
      )
      @user_comments = @recipe.impressions.page(params[:page]).per(5)
    else
      flash[:danger] = "レシピが見つかりませんでした"
      redirect_to root_url
    end
  end
  
  private
  
    #Recipeのストロングパラメーター
    def recipe_params
      params.require(:recipe).permit(:name, :comment, :image, :image_cache)
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
  
    #ログイン済ユーザーかどうか確認
    def logged_in_author
      unless logged_in?
        store_location
        flash[:danger] = "レシピの閲覧・投稿・編集にはログインが必要です。"
        redirect_to login_url
      end
    end
    
    #URLからレシピＩＤを取得。
    def recipe_author
      @recipe = Recipe.find_by(id: params[:id])
      @user = @recipe.user
    end
    
    #フォームのパラメーターからレシピIDを取得
    def recipe_author_via
      @recipe = Recipe.find_by(id: params[:recipe_id])
      @user = @recipe.user
    end
    
    #recipe_authorメソッドでユーザー情報を取得
    def correct_author
      recipe_author
      redirect_to(root_url) unless current_user?(@user)
    end
    
    #recipe_author_viaメソッドでユーザー情報を取得
    def correct_author_via
      recipe_author_via
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/views/recipes/_book.html.erb
<% if @recipe.present? %>
  <% recipe = @recipe %>
<% else %>
  <% recipe = book_recipe %>
<% end %>
<%= form_with url: books_path, class: "inline-block" do |f| %>
  <%= hidden_field_tag :recipe_id, recipe.id %>
  <%= button_tag type: "submit", class: "book-icon" do %>
    <%= icon('far','bookmark') %>
  <% end %>
<% end %>

app/views/recipes/_empty_procedure_form.html.erb
<% 5.times.with_index do |i| %>
  <div class="procedure-list flex flex-left">
    <%= render "procedures_show", i: i %>
  </div>
  <dt><a>手順を変更する</a></dt>
  <dd>
    <div class="flex">
      <div>
        <%= "#{(i+1)}"%>:
      </div>
      <div class="procedure-input-textarea">
        <%= form_with model: @procedure, url: procedures_path do |form| %>
          <%= hidden_field_tag :recipe_id, @recipe.id %>
          <%= form.text_area :content, placeholder: "手順を入力しましょう", value: procedure.content if procedure.content.present? %>
          <%= form.hidden_field :number, value: "#{(i+1)}" %>
          <%= form.submit "保存" %>
        <% end %>
      </div>
      
      <div class="flex flex-end">
        <% unless i == 0 %>
          <%= form_with url: procedures_change_before_path do |form| %>
            <%= hidden_field_tag :recipe_id, @recipe.id %>
            <%= hidden_field_tag :number, "#{(i+1)}" %>
            <%= form.submit "↑", class: "change_content_button" %>
          <% end %>
        <% end %>
        
        <% unless i == @recipe.procedure.count - 1 %>
          <%= form_with url: procedures_change_after_path do |form| %>
            <%= hidden_field_tag :recipe_id, @recipe.id %>
            <%= hidden_field_tag :number, "#{(i+1)}" %>
            <%= form.submit "↓", class: "change_content_button" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </dd>
<% end %>

app/views/recipes/_ingredient_form.html.erb
<div class="ingredient-form">
  <div class="ingredients-show">
    <% if @recipe.ingredient.empty? %>
      <p>材料を入力しましょう</p>
    <% else %>
      <%= render "ingredients_show" %>
    <% end %>
  </div>
  
  <dt class="pr10"><a>材料を変更する</a></dt>
  <dd>
    <%= form_with model: @ingredients, url: ingredients_path do |form| %>
      <%= hidden_field_tag :recipe_id, @recipe.id %>
      
      <% @ingredients.collection.each_with_index do |ingredient, i| %>
        <% existing_ingredient = @recipe.ingredient.find_by(number: "#{i+1}") %>
        <%= fields_for 'ingredients[]', ingredient do |field| %>
          
          <% if existing_ingredient && existing_ingredient.name.present? %>
            <%= field.text_field :name, value: existing_ingredient.name %>
            <%= field.text_field :amount, value: existing_ingredient.amount %>
          <% else %>
            <%= field.text_field :name, placeholder: "材料名" %>
            <%= field.text_field :amount, placeholder: "量" %>
          <% end %>
          
        <% end %>
      <% end %>
      <%= form.submit %>
    <% end %>
   
  </dd>
</div>

app/views/recipes/_ingredients_show.html.erb
<% @recipe.ingredient.each do |ingredient| %>
  <% if ingredient.name.present? %>
    <div class="ingredient-list flex flex-between">
      <div><%= ingredient.name %></div>
      <div><%= ingredient.amount %></div>
    </div>
  <% end %>
<% end %>

app/views/recipes/_new_procedure_form.html.erb
<div class="procedure-list flex flex-left">
  <div id="procedure-number-<%= (i+1) %>"></div>
  <div id="procedure-show-<%= (i+1) %>" ></div>
</div>

app/views/recipes/_procedure_form.html.erb
<% if @recipe.procedure.count == 0 %>
  <% loop_count = 4 %>
<% else %>
  <% loop_count = @recipe.procedure.count + 1 %>
<% end %>

<% loop_count.times.with_index do |i| %>
  <% procedure = @recipe.procedure.find_by(number: (i+1)) %>
  <!--ループエンド時の処理-->
  <% if loop_count == (i+1) %>
    <div class="btn-wrapper">
      <%= form_with model: @procedure, url: procedures_path do |form| %>
        <%= hidden_field_tag :recipe_id, @recipe.id %>
        <%= form.hidden_field :content, value: "テスト" %>
        <%= form.hidden_field :number, value: "#{(i+1)}" %>
        <%= form.submit "追加する" %>
      <% end %>
    </div>
  <!--ループ回数と合致するprocedureが存在した場合-->
  <% elsif procedure %>
  <div class="procedure-box">
    <div class="procedure-list flex flex-left">
      <%= render "recipes/procedures_show", {i: i, procedure: procedure} %>
    </div>
    <dt class="pr10"><a>手順を変更する</a></dt>
    <dd>
      
        <div class="procedure-input-textarea">
          <%= form_with model: @procedure, url: procedures_path do |form| %>
            <%= hidden_field_tag :recipe_id, @recipe.id %>
            <%= form.text_area :content, placeholder: "手順を入力しましょう", value: procedure.content if procedure.content.present? %>
            <%= form.hidden_field :number, value: "#{(i+1)}" %>
            <%= form.submit "保存" %>
          <% end %>
        </div>
        
        <div class="flex flex-end">
          <% unless i == 0 %>
            <%= form_with url: procedures_change_before_path do |form| %>
              <%= hidden_field_tag :recipe_id, @recipe.id %>
              <%= hidden_field_tag :number, procedure.number %>
              <%= form.submit "↑", class: "change_content_button" %>
            <% end %>
          <% end %>
          
          <% unless i == @recipe.procedure.count %>
            <%= form_with url: procedures_change_after_path do |form| %>
              <%= hidden_field_tag :recipe_id, @recipe.id %>
              <%= hidden_field_tag :number, procedure.number %>
              <%= form.submit "↓", class: "change_content_button" %>
            <% end %>
          <% end %>
          
        </div>
        <p class="text-right">
          <%= link_to "削除", procedure_path(procedure), method: :delete %>
        </p>
      
    </dd>
  </div>
  <!--ループ回数と合致するprocedureが存在しない場合-->
  <% else %>
    <div class="procedure-list flex flex-left">
      <div><%= "#{(i+1)}"%>:</div>
      <div id="procedure-show-<%= "#{(i+1)}" %>" ></div>
    </div>
    
    <dt class="pr10"><a>手順を変更する</a></dt>
    
    <dd>
      <div class="flex">
        <div>
          <%= "#{(i+1)}"%>:
        </div>
        <div class="procedure-input-textarea">
          <%= form_with model: @procedure, url: procedures_path do |form| %>
            <%= hidden_field_tag :recipe_id, @recipe.id %>
            <%= form.text_area :content, placeholder: "手順を入力しましょう" %>
            <%= form.hidden_field :number, value: "#{(i+1)}" %>
            <%= form.submit "保存" %>
          <% end %>
        </div>
        
        <div class="flex flex-end">
          <% unless i == 0 %>
            <%= form_with url: procedures_change_before_path do |form| %>
              <%= hidden_field_tag :recipe_id, @recipe.id %>
              <%= hidden_field_tag :number, "#{(i+1)}" %>
              <%= form.submit "↑", class: "change_content_button" %>
            <% end %>
          <% end %>
          
          <% unless i == 4 %>
            <%= form_with url: procedures_change_after_path do |form| %>
              <%= hidden_field_tag :recipe_id, @recipe.id %>
              <%= hidden_field_tag :number, "#{(i+1)}" %>
              <%= form.submit "↓", class: "change_content_button" %>
            <% end %>
          <% end %>
          <%= link_to "削除" %>
        </div>
      </div>
    </dd>
  <% end %>
<% end %>

app/views/recipes/_procedures_show.html.erb
<div><%= "#{(i+1)}"%>:</div>
<div id="procedure-show-<%= procedure.number %>" ><%= procedure.content %></div>

app/views/recipes/_recipe_comment_form.html.erb
<div id="recipe-comment-show">
  <% if @recipe.comment.present? %>
  	<%= @recipe.comment %>
  <% else %>
  	<p>コメントを入力しましょう。</p>
  <% end %>
</div>
<dt><a>コメントを変更する</a></dt>
<dd>
  <%= form_for(@recipe, remote: true) do |form| %>
    <%= form.text_area :comment, placeholder: "コメントを入力しましょう", value: @recipe.comment %>
    <div class="btn-right">
      <%= form.submit "保存" , class: "btn mini-btn"%>
    </div>
  <% end %>
</dd>

app/views/recipes/_user_comment.html.erb
<% if @user_comments.present? %>
	<% @user_comments.each do |comment| %>
		<p><%= comment.comment %></p>
			<%= link_to "#{comment.user.name}", user_path(comment.user) %>
			<%= comment.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
			<% if current_user == comment.user %>
				<%= link_to "削除", impression_path(comment),
						method: :delete, data: {confirm: "本当に削除しますか？"} %>
			<% end %>
		
	<% end %>
<% end %>
<%= paginate @user_comments %>

app/views/recipes/edit.html.erb
<div class="recipes-edit content-inner">
  
  <section class="recipe-name">
    <div class="label gray-label mb-s">
      <h3>レシピの名前</h3>
    </div>
    <div class="content-inner">
      <h1 id="recipe-title"><%= @recipe.name %></h1>
      <dt><a>名前を変更する</a></dt>
      <dd>
       <%= render "recipes/edit/nameform" %>
      </dd>
    </div>
  </section>
  
  <section class="recipe-comment">
    <div class="label gray-label mb-s">
      <h3>コメント</h3>
    </div>
    <div class="content-inner">
      <%= render "recipes/edit/commentform" %>
    </div>
  </section>
  
  <section>
    <div class="label gray-label mb-s">
      <h3>写真</h3>
    </div>
    <div class="text-center recipes-edit-img mb-s">
      <%= image_tag @recipe.image.url %>
    </div>
    <div class="btn-center mb-l">
      <%= render "recipes/edit/uploader" %>
    </div>
  </section>
    
  <section>
    <div class="label gray-label mb-s">
      <h3>材料</h3>
    </div>
    <%= render "recipes/ingredients/form" %>
  </section>
  
  <section class="mb-ll">
    <div class="label gray-label mb-s">
      <h3>調理の手順</h3>
    </div>
    <div id="procedure-form">
      <%= render "recipes/procedures/form" %>
    </div>
  </section>


  <div class="btn-center mb-ss">
    <%= render "recipes/edit/releaseform" %>
  </div>
  <div class="text-center mb-ss">
    <p>or</p>
  </div>
  <div class="btn-center mb-l">
    <%= render "recipes/edit/privateform"%>
  </div>

  <div class="btn-center">
    <%= link_to "レシピを削除", recipe_path(@recipe), method: :delete, data: {confirm: "本当に削除しますか？"} %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="content-inner">
  <div class="label gray-label">
    <% if @keyword.nil? %>
      <h3>レシピ一覧(<%= @recipes_count.count %>件)</h3>
    <% elsif @keyword.empty? %>
      <h3>レシピ一覧(<%= @recipes_count.count %>件)</h3>
    <% else %>
      <h3>"<%= @keyword %>"の検索結果(<%= @recipes_count.count %>件)</h3>
    <% end %>
  </div>
  <div>
    <% if @recipes.present? %>
      <% @recipes.each do |recipe| %>
        <%= render "layouts/recipe_list", recipe: recipe %>
      <% end %>
    <% else %>
      <p>"<%= @keyword %>"を含むレシピは見つかりませんでした(><;)</p>
      <p>まだ検索機能が弱いので許してください(><;)</p>
    <% end %>
    <%= paginate @recipes %>
  </div>
</div>

app/views/recipes/liked.html.erb
<h1>このレシピをイイネしたユーザー</h1>
<table class="table table-striped">
  <tr><th>ユーザー名</th></tr>
  <% @liked_user.each do |u| %>
    <tr>
      <td>
        <%= link_to "#{User.find_by(id: u.user_id).name}", user_path(id: u.user_id) %>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @liked_user %>

app/views/recipes/new.html.erb
<div class="content-inner">
  <h1 class="mb-s">料理の名前を入力してください</h1>
  <%= form_for(@recipe) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.text_area :name, placeholder: "例：スベリヒユのおひたし" %>
    <div class="btn-center">
      <%= f.submit "レシピ入力に進む", class: "btn large-btn" %>
    </div>
  <% end %>
</div>

app/views/recipes/update.js.erb
$("#recipe-title").html( "<%= escape_javascript(@recipe.name)%>" );
$("#recipe-comment-show").html( "<%= escape_javascript(@recipe.comment) %>" );