config/routes.rb
Rails.application.routes.draw do
  
  #avtive_admin用のルート
  ActiveAdmin.routes(self)
  
  root "static_pages#home"
  get "/about", to:"static_pages#about"
  get '/signup', to: "users#new"
  post "/signup", to: "users#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/auth/:provider/callback", to: 'sessions#twitter_create', as: 'tlogin'
  delete "/logout", to: "sessions#destroy"
  
  resources :users
  
  resources :recipes do
    member do
      get :liked #レシピをイイネしたユーザーの一覧
      patch :release #公開・非公開を決めるカラム
    end
  end
  patch "recipes/:id/edit", to: "recipes#update", as: "update_recipe"

  resources :ingredients, only: :create
  
  resources :procedures, only: :create
  patch "procedures/update", to: "procedures#update"
  delete "procedures/destroy", to: "procedures#destroy"
  post "procedures/change_after", to: "procedures#change_after"
  post "procedures/change_before", to: "procedures#change_before"
  
  resources :likes, only: [:create, :destroy]
  
  resources :books, only: [:create,:destroy]
  
  resources :impressions, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token #仮想の属性remember_tokenを作成
  before_save { email.downcase! } #saveする前にemailを小文字化する(一意性の確保)
  
  #画像アップロード
  mount_uploader :image, ImageUploader
  validate :image_size

  #バリデーション
  validates :name, presence: true, length: {maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255 },
                    format: {with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 },allow_nil: true
  validates :profile_text, length: {maximum: 255 }
  
  #リレーション
  has_many :recipes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :impressions, dependent: :destroy
  
  #twitterログイン用のメソッド
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    image = auth[:info][:image]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.email = User.dummy_email(auth)
      user.password = User.new_token
      user.remote_image_url = image
    end
  end
  
  class << self
    
    #渡された文字列をBcryptで暗号化して返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    
    #ランダムなトークンを生成
    def new_token
      SecureRandom.urlsafe_base64
    end
    
  end
  
  #永続セッションのためにユーザーをデータベースに記憶
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  #渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  #ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #レシピをイイネする
  def like(recipe)
    likes.create(recipe_id: recipe.id)
  end
  
  #レシピのイイネを取り消す
  def unlike(recipe)
    likes.find_by(recipe_id: recipe.id).destroy
  end
  
  #ユーザーがレシピをイイネしていたらtrueを返す
  def like?(recipe)
    likes.find_by(recipe_id: recipe.id).present?
  end
  
  #レシピをブックマークする
  def book(recipe)
    books.create(recipe_id: recipe.id)
  end
  
  #レシピのブックマークを取り消す
  def unbook(recipe)
    books.find_by(recipe_id: recipe.id).destroy
  end
  
  #ユーザーがレシピをブックマークしていたらtrueを返す
  def book?(recipe)
    books.find_by(recipe_id: recipe.id).present?
  end
  
  #ユーザーがレシピにコメントする
  def write_comment(recipe, comment)
    impressions.create(recipe_id: recipe.id, comment: comment)
  end
  
  private

  def image_size
    if image.size > 3.megabytes
      errors.add(:image, "画像サイズは3MB以内です")
    end
  end

  #twitterログイン用ダミーアドレス生成
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def show
    @user = User.find_by(id: params[:id])
    if @user.present?
      @recipes_count = @user.recipes.where(release: true)
      @recipes = @recipes_count.order(id: "desc").page(params[:page]).per(5)
      @draft_recipes_count = @user.recipes.where(release: false)
      @draft_recipes = @draft_recipes_count.order(id: "desc").page(params[:draft_page]).per(5)
      @like_recipes_count = @user.likes
      @like_recipes = @like_recipes_count.order(id: "desc").page(params[:like_page]).per(5)
      @book_recipes_count = @user.books
      @book_recipes = @book_recipes_count.order(id: "desc").page(params[:book_page]).per(5)
    else
      flash[:danger] = "ユーザーが見つかりませんでした"
      redirect_to root_url
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "WildRecipeへようこそ！"
      redirect_to @user
    else
      render "new"
    end
  end
  
  #@userはbefore_actionのcorrect_userで定義
  def edit
    @user.image.cache! unless @user.image.blank?
  end
  
  #@userはbefore_actionのcorrect_userで定義
  def update
    if @user.update_attributes(user_params)
        respond_to do |format|
          format.html { redirect_to @user }
          format.js
        end
    else
      render "edit"
    end
  end

  private
    
    #このparamsハッシュでは:user属性を必須とし、許可した属性以外をブロックする(strong parameters)
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation,:profile_text,:image)
    end
    
    #beforeアクション
    
    #ログイン済ユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
    #正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    #管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_booked_recipe.html.erb
<% if @book_recipes.present? %>
  <% @book_recipes.each do |book_recipe| %>
    <%= render "layouts/recipe_list", recipe: book_recipe.recipe %>
  <% end %>
<% else %>
  <p>まだレシピをブックマークしていません</p>
<% end %>

app/views/users/_draft_recipe.html.erb
<% if @draft_recipes.present? %>
  <% @draft_recipes.each do |draft_recipe| %>
    <%= render "layouts/recipe_list", recipe: draft_recipe %>
  <% end %>
  <%= paginate @draft_recipes, param_name: "draft_page" %>
<% else %>
  <p>未公開のレシピはありません</p>
<% end %>

app/views/users/_liked_recipe.html.erb
<% if @like_recipes.present? %>
  <% @like_recipes.each do |like_recipe| %>
    <%= render "layouts/recipe_list", recipe: like_recipe.recipe %>
  <% end %>
<% else %>
  <p>まだレシピをイイネしていません</p>
<% end %>

app/views/users/_posted_recipe.html.erb
<% if @recipes.present? %>
  <% @recipes.each do |recipe| %>
    <%= render "layouts/recipe_list", recipe: recipe %>
  <% end %>
<% else %>
 <p>まだレシピを投稿していません</p>
<% end %>

app/views/users/_profile.html.erb
<p>
  <div class="profile_ajax">
    <%= @user.profile_text %>
  </div>
</p>

<% if current_user == @user %>
  <%= link_to "ユーザー情報の変更", edit_user_path(@user) %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "プロフィールの変更") %>
<section class="user-edit text-center mb-l">
  <h1 class="mb-m">プロフィールの変更</h1>
  
  <div class="user-icon">
    <%= image_tag @user.image.url %>
  </div>
  <%= form_with model: @user, url: user_path, local: true do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>
    <%= f.hidden_field :image_cache %>
    <div class="btn-center">
      <%= button_tag type: "submit", class: "clear-btn mb-l" do %>
        <%= icon('fas','camera') %><%= "イメージを登録" %>
      <% end %>
    </div>
  <% end %>
  <%= form_for(@user,html: {class: "inline"}) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    
    <p><%= f.label :name, "ニックネーム" %></p>
    <%= f.text_field :name, class: "session-form mb-s" %>
    
    <p><%= f.label :profile_text, "プロフィール文" %></p>
    <%= f.text_field :profile_text, class: "session-form mb-s" %>
    
    <% if @user.provider.nil? %>
      <p><%= f.label :email, "メールアドレス" %></p>
      <%= f.email_field :email, class: "session-form mb-s" %>
      
      <p><%= f.label :password, "パスワード" %></p>
      <%= f.password_field :password, class: "session-form mb-s" %>
      
      <p><%= f.label :password_confirmation, "パスワードの再入力" %></p>
      <%= f.password_field :password_confirmation, class: "session-form mb-m" %>
    <% end %>
    <%= f.submit "変更", class: "btn large-btn" %>
  <% end %>
</section>

<div class="text-center">
  <%= link_to "プロフィールへ戻る", @user %>
</div>

app/views/users/new.html.erb
<% provide(:title,"サインアップ")%>

<section class="signup text-center">
  <h1 class="mb-m">サインアップ</h1>
  <%= form_for(@user, url: signup_path, html: {class: "inline"}) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    
    <%= f.text_field :name, class: "session-form mb-s", placeholder: "ニックネーム" %>
    
    <%= f.email_field :email, class: "session-form mb-s", placeholder: "Eメールアドレス" %>
    
    <%= f.password_field :password, class: "session-form mb-s", placeholder: "パスワード" %>

    <%= f.password_field :password_confirmation, class: "session-form mb-m", placeholder: "パスワードの再入力" %>
    
    <%= f.submit "アカウント登録", class: "btn large-btn" %>
  <% end %>
</section>

app/views/users/show.html.erb
<% provide(:title, "ユーザープロフィール")%>
<div class="content-inner">
  <div class="flex mb-m">
    <div class="user-icon">
      <%= image_tag @user.image.url %>
    </div>
    <div class="profile_text">
      <h3><%= @user.name %></h3>
      <%= render "profile" %>
    </div>
  </div>
  <ul class="flex mb-s">
    <li class="tab profile-tab is-active">投稿(<%= @recipes_count.count %>)</li>
    <li class="tab profile-tab">イイネ(<%= @like_recipes_count.count %>)</li>
    <li class="tab profile-tab">ブクマ(<%= @book_recipes_count.count %>)</li>
    <% if current_user == @user %>
      <li class="tab profile-tab">下書き(<%= @draft_recipes_count.count %>)</li>
    <% end %>
  </ul>
  
  <div class="profile-panel-group content-inner">
    <section class="panel is-show">
      <h3>投稿したレシピ(<%= @recipes_count.count %>)</h3>
      <%= render "posted_recipe" %>
      <%= paginate @recipes %>
    </section>
  
    <section class="panel">
      <h3>イイネしたレシピ(<%= @like_recipes_count.count %>)</h3>
      <%= render "liked_recipe" %>
      <%= paginate @like_recipes, param_name: "like_page" %>
    </section>
  
    <section class="panel">
      <h3>ブックマークしたレシピ(<%= @book_recipes_count.count %>)</h3>
      <%= render "booked_recipe" %>
      <%= paginate @book_recipes, param_name: "book_page" %>
    </section>
  
    <section class="panel">
      <% if current_user == @user %>
        <h3>未公開のレシピ(<%= @draft_recipes_count.count %>)</h3>
        <%= render "draft_recipe" %>
      <% end %>
    </section>
  </div>
</div>

app/views/users/update.js.erb
$(".profile_ajax").html("<%= @user.profile_text %>")