config/routes.rb
Rails.application.routes.draw do
  
  #avtive_admin用のルート
  ActiveAdmin.routes(self)
  
  root "static_pages#home"
  get "/about", to:"static_pages#about"
  get '/signup', to: "users#new"
  post "/signup", to: "users#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/auth/:provider/callback", to: 'sessions#twitter_create', as: 'tlogin'
  delete "/logout", to: "sessions#destroy"
  
  resources :users
  
  resources :recipes do
    member do
      get :liked #レシピをイイネしたユーザーの一覧
      patch :release #公開・非公開を決めるカラム
    end
  end
  patch "recipes/:id/edit", to: "recipes#update", as: "update_recipe"

  resources :ingredients, only: :create
  
  resources :procedures, only: :create
  patch "procedures/update", to: "procedures#update"
  delete "procedures/destroy", to: "procedures#destroy"
  post "procedures/change_after", to: "procedures#change_after"
  post "procedures/change_before", to: "procedures#change_before"
  
  resources :likes, only: [:create, :destroy]
  
  resources :books, only: [:create,:destroy]
  
  resources :impressions, only: [:create, :destroy]
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :recipe
  
  #コンテンツを入れ替える
  def self.change_content(procedure = nil, change_procedure = nil)
    begin
      temp_content = procedure.content
      procedure.update_attributes(content: change_procedure.content)
      change_procedure.update_attributes(content: temp_content)
    rescue => e
      return false
    end
  end
  
  #ナンバーが次に大きいレコードを取得
  def next_number
    begin
      Procedure.where("(number > ?) AND (recipe_id = ?)", self.number, self.recipe_id).order("number ASC").first
    rescue => e
      return false
    end
  end
  
  #ナンバーが次に小さいレコードを取得
  def previous_number
    begin
      Procedure.where("(number < ?) AND (recipe_id = ?)", self.number, self.recipe_id).order("number DESC").first
    rescue => e
      return false
    end
  end
  
  #最後のナンバーを持つレコードを返す,レコードが無ければゼロを返す
  def self.last_number(recipe)
    proces = recipe.procedure
    if proces.empty?
      return 0
    else
      recipe.procedure.order(number: "DESC").first.number
    end
  end
  
  #ナンバーが下のレコードのナンバーを-1して削除する
  def destroy_procedure
    self.lower_number.each do |procedure|
      procedure.update_attributes(number: (procedure.number - 1))
    end
    self.destroy
  end
  
  #自分が持つナンバーより下のナンバーを持つレコードを取得
  def lower_number
    Procedure.where("(number > ?) AND (recipe_id = ?)", self.number, self.recipe_id)
  end
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  #リレーション
  belongs_to :user
  has_many :ingredient, dependent: :destroy
  has_many :procedure, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :impressions, dependent: :destroy
  
  #アップローダー
  mount_uploader :image, ImageUploader
  validate :image_size
  
  #バリデーション
  validates :name,presence: true, length: {maximum: 20}
  
  private
  
    #アップロードされた画像のサイズをバリデーション
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "画像サイズは5MB以内です")
      end
    end
  
    #キーワードに対応したレシピを返す
    def self.search(search)
      #検索ワードが空なら公開レシピをすべて取得
      return Recipe.where(release: true) unless search
      #検索ワードに似たレシピを返す
      Recipe.where(release: true).where("name LIKE ?", "%#{search}%")
    end
    
    #レシピを時系列で返す
    def self.latest(limit_number = nil)
      #取得数の指定がなければすべてのレコードを取得
      return Recipe.where(release: true).order(created_at: "DESC") unless limit_number
      #指定された数のレコードを取得
      Recipe.where(release: true).order(updated_at: "DESC").limit(limit_number)
    end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :logged_in_author
  before_action :correct_author_via, only: [:create, :change_after, :change_before]
  before_action :procedure_correct_author, only: [:update, :destroy]
  
  def create
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @number = Procedure.last_number(@recipe) + 1
    @procedure = @recipe.procedure.build(procedure_params)
    @procedure.number = @number 
    respond_to do |format|
      if @procedure.save
        format.html { redirect_to edit_recipe_path(@recipe) }
        format.js
      else
        format.html { redirect_to edit_recipe_path(@recipe) }
        format.js
      end
    end
  end
  
  def update
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @procedure = @recipe.procedure.find_by(number: params[:number])
    respond_to do |format|
      if @procedure.update_attributes(procedure_params)
        format.html { redirect_to edit_recipe_path(@recipe)}
        format.js
      else
        format.html { redirect_to edit_recipe_path(@recipe)}
        format.js
      end
    end
  end
        
  def change_after
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @procedure = @recipe.procedure.find_by(number: params[:number])
    @next_procedure = @procedure.next_number
    respond_to do |format|
      if @next_procedure
        Procedure.change_content(@procedure, @next_procedure)
        @file_exist = true
        format.html { redirect_to edit_recipe_path(@recipe)}
        format.js
      else
        @file_exist = false
        format.html { redirect_to edit_recipe_path(@recipe)}
        format.js
      end
    end
  end
  
  def change_before
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @procedure = @recipe.procedure.find_by(number: params[:number])
    @previous_procedure = @procedure.previous_number
    respond_to do |format|
      if @previous_procedure
        Procedure.change_content(@procedure, @previous_procedure)
        @file_exist = true
        format.html { redirect_to edit_recipe_path(@recipe)}
        format.js
      else
        @file_exist = false
        format.html { redirect_to edit_recipe_path(@recipe)}
        format.js
      end
    end
  end
  
  def destroy
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @number = params[:number]
    @procedure = @recipe.procedure.find_by(number: @number)
    respond_to do |format|
      if @recipe.procedure.count > 1
        @procedure.destroy_procedure
        format.html { redirect_to edit_recipe_path(@recipe) }
        format.js
      else
        @procedure.update_attributes(content: "")
        format.html { redirect_to edit_recipe_path(@reipe) }
        format.js
      end
    end
  end
  
  private 
  
  def procedure_correct_author
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @user = @recipe.user
  end
  
  def procedure_params
    params.require(:procedure).permit(:number, :content )
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_author, only: [:new, :create, :edit]
  before_action :correct_author, only:[:edit, :update, :release, :destroy]
  
  def index
    @keyword = params[:search] 
    @recipes_count = Recipe.search(@keyword)
    @recipes = @recipes_count.order(updated_at: "DESC").page(params[:page]).per(20)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      @recipe.procedure.create(number: 1, content: "")
      @recipe.ingredient.create(number: 1)
      redirect_to edit_recipe_path(@recipe)
    else
      render "new"
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
    @ingredients = IngredientCollection.new( [], @recipe)
    @procedures = @recipe.procedure.order(number: "ASC")
    @procedure = @recipe.procedure.build
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      respond_to do |format|
        format.html {redirect_to edit_recipe_path(@recipe)}
        format.js
      end
    else
      @ingredients = IngredientCollection.new( [], @recipe)
      @procedures = @recipe.procedure.order(number: "ASC")
      render "edit"
    end
  end
  
  #@recipe,@userはcorrect_userで設定
  def destroy
    @recipe.destroy
    flash[:success] = "レシピを削除しました"
    redirect_to user_path(@user)
  end
  
  def release
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(release: params[:release])
      if @recipe.release == true
        flash[:success] = "レシピを公開しました"
        redirect_to recipe_path(@recipe)
      else
        flash[:success] = "レシピを下書きにしました"
        redirect_to user_path(id: @recipe.user_id)
      end
    else
      render "edit"
    end
  end
  
  def liked
    @recipe = Recipe.find(params[:id])
    @liked_user = @recipe.likes.page(params[:page])
  end
  
  def show
    @recipe = Recipe.find_by(id: params[:id])
    if @recipe.present?
      @tweet_url = URI.encode(
        "http://twitter.com/intent/tweet?original_referer=" +
        request.url +
        "&url=" +
        request.url +
        "&text=" +
        @recipe.name + "のレシピを見ています！"
      )
      @user_comments = @recipe.impressions.page(params[:page]).per(5)
    else
      flash[:danger] = "レシピが見つかりませんでした"
      redirect_to root_url
    end
  end
  
  private
  
    #Recipeのストロングパラメーター
    def recipe_params
      params.require(:recipe).permit(:name, :comment, :image, :image_cache)
    end

end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  
    #ログイン済ユーザーかどうか確認
    def logged_in_author
      unless logged_in?
        store_location
        flash[:danger] = "レシピの閲覧・投稿・編集にはログインが必要です。"
        redirect_to login_url
      end
    end
    
    #URLからレシピＩＤを取得。
    def recipe_author
      @recipe = Recipe.find_by(id: params[:id])
      @user = @recipe.user
    end
    
    #フォームのパラメーターからレシピIDを取得
    def recipe_author_via
      @recipe = Recipe.find_by(id: params[:recipe_id])
      @user = @recipe.user
    end
    
    #recipe_authorメソッドでユーザー情報を取得
    def correct_author
      recipe_author
      redirect_to(root_url) unless current_user?(@user)
    end
    
    #recipe_author_viaメソッドでユーザー情報を取得
    def correct_author_via
      recipe_author_via
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/views/recipes/procedures/_change_content_btn.html.erb
<div class="flex flex-end">
	<div class="change-content-btn">
		<%= form_with url: procedures_change_before_path do |form| %>
			<%= hidden_field_tag :recipe_id, @recipe.id %>
			<%= hidden_field_tag :number, procedure.number, class: "hidden-number" %>
			<%= button_tag type: "submit", class: "func-btn" do %>
				<%= icon('fas','arrow-alt-circle-up') %>
			<% end %>
		<% end %>
	</div>
	<div class="change-content-btn">
		<%= form_with url: procedures_change_after_path do |form| %>
			<%= hidden_field_tag :recipe_id, @recipe.id %>
			<%= hidden_field_tag :number, procedure.number, class: "hidden-number" %>
			<%= button_tag type: "submit", class: "func-btn" do %>
				<%= icon('fas','arrow-alt-circle-down') %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/recipes/procedures/_form.html.erb
<section>
  <% @procedures.each do |procedure| %>
    <% unless procedure.content.nil? %>
      <div class="formbox procedure-box" data-formno="<%= procedure.number %>" >
        <div class="procedure-list flex flex-left">
          <div class="formbox-no"><%= procedure.number %></div>:
          <div class="procedure-show" name="number[<%= procedure.number %>]"><%= procedure.content %></div>
        </div>
  
        <div class="procedure-input-textarea">
          <%= form_with model: @procedure, url: procedures_update_path, method: :patch do |form| %>
            <%= hidden_field_tag :recipe_id, @recipe.id %>
            <%= hidden_field_tag :number, procedure.number, class: "hidden-number" %>
            <%= form.text_area :content, placeholder: "手順を入力しましょう", value: procedure.content, id: "textarea#{procedure.number}" %>
            <div class="btn-center">
              <%= form.submit "保存する", class: "btn mini-btn" %>
            </div>
          <% end %>
        </div>

        <div class="flex flex-between content-inner">
          <%= form_with url: procedures_destroy_path, method: :delete do |form| %>
            <%= hidden_field_tag :recipe_id, @recipe.id %>
            <%= hidden_field_tag :number, procedure.number, class: "hidden-number" %>
            <%= form.submit "削除", class: "clear-btn" %>
           <% end %>
           
          <%= render "recipes/procedures/change_content_btn", procedure: procedure %>
        </div>
        
        
      
      </div>
    <% end %>
  <% end %>
</section>
<div class="btn-center">
  <%= form_with model: @procedure, url: procedures_path do |form| %>
    <%= hidden_field_tag :recipe_id, @recipe.id %>
    <%= form.hidden_field :content, value: "" %>
    <%= button_tag type: "submit", class: "btn clear-btn" do %>
      <%= icon('fas','plus-circle') %><%= "手順を追加" %>
    <% end %>
  <% end %>
</div>

app/views/recipes/procedures/_show.html.erb
<div><%= "#{(i+1)}"%>:</div>
<div id="procedure-show-<%= procedure.number %>" ><%= procedure.content %></div>